language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t lewavesi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lewavesi/docker-react npm run test